### ISSUE TITLE
How to install avstplg and how to use it?

### ISSUE THREAD

**Issue by foxrus** [thesofproject/avsdk#8]
How to install avstplg and how to use it?

**Comment by crojewsk-intel** [comment]
There is no installation per se. Just download and `make`. The building instructions for avstplg and provided on the [main](https://github.com/thesofproject/avsdk#building) branch while for itt that targets skylake-driver are provided on the [for-skylake-driver](https://github.com/thesofproject/avsdk/tree/for-skylake-driver#building) branch.

**Comment by crojewsk-intel** [comment]
I admit that initially the building instructions for the itt tool were missing. We have addressed that with [itt: Add building instructions to README](https://github.com/thesofproject/avsdk/pull/5).

Given that the instructions are there and the actual problem reported by user is tracked at [No sound on avs_max98357a](https://github.com/thesofproject/avs-topology-xml/issues/12), closing as completed.
